import Head from "next/head";

import React from "react";
import { homeContent } from "../components/ContentJson";
import Hero from "../components/home/Hero";
export const Home = () => {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Hero />
      {/* <Hero {...homeContent} /> */}
    </>
  );
};
export default Home;
